### ISSUE TITLE
Suggestion for Message Formatting

### ISSUE THREAD

**Issue by ps-balucan** [digitalsirkeith/coe151#1]
The main format of messages will be in JSON.
Refer [here](https://www.w3schools.com/python/python_json.asp) for more information.

These headers will be found in all messages. Special commands will contain extra elements in the data field of the JSON depending on the type of command. (Commands specified at the github link) The following JSON formats are used for Serverbound "data"(Client to server)
### Serverbound Messages
At the very start, clients will attempt to connect to the server by sending a Login request containing their proposed username. They will then wait for the server to send a SetUsername response with status OK before proceeding to send chat messages/other commands to the server.
1. Login 
`{ "mtp": "Login", "data": {"name": "Bob"} }` 
Response 1: `{ "mtp": "AssignUsername", "data": {"name": "Bob"} , "status" : "OK"}`
Response 2: `{ "mtp": "AssignUsername", "data": {"name": "Bob"} , "status" : "DuplicateError"}`
A duplicate error indicates that the server has found a user with the same username already logged in. The client attempting to join will keep sending Login requests till an OK response is sent by the server.
2. SetUsername
Similar to the Login scheme, the server will send a status response indicating if the username of the client was changed successfully. 
Client request:
`{ "mtp": "SetUsername", "data": {"name": "Bob"}}`
Server response:
`{ "mtp": "SetUsername", "data": {"name": "Bob"}, "status": "OK" }`
3. RequestUserInfo
`{ "mtp": "RequestUserInfo", "data": {"name": "Bob"} }`
4. RequestLocalTime
`{ "mtp": "RequestLocalTime", "data": {}`
5. WhisperToUser
`{ "mtp": "WhisperToUser", "data" :{"from" : "Bob",  "to": ["claudyne",  "philippe",  "keith"], "message": "This is a pm"  } }`
6. SendChat
`{ "mtp": "SendChat", "data" : { "message": "Hello World!"  } }`
7. RequestOnlineList - Include all users including the requestor
`{ "mtp": "RequestOnlineList", "data" : {} }`
8. Disconnect
`{ "mtp": "Disconnect", "data" : {} }`
Will be sent from client every time it closes.
9. KickUser - request the server to kick a certain user
`{ "mtp": "KickUser", "data" : { "name" : "user99" } }`
10. MuteUser - request for server to ignore all sendchat messages from a user
`{ "mtp": "MuteUser", "data" : { "name" : "user99" } }`
10. UnmuteUser- request for server to stop ignoring all sendchat messages from a user
`{ "mtp": "UnmuteUser", "data" : { "name" : "user99" } }`
12. SetAsAdmin - name is the name of the user you want to promote to admin
`{ "mtp": "SetAsAdmin", "data" : { "name" : "user99" } }`
13. KeepAlive

Clientbound (server to client)
  1. AssignUsername 
`{ "mtp": "AssignUsername", "data" : {"name": "Bob"}, "status" : "OK" }`
`{ "mtp": "AssignUsername", "data" : {"name": "Bob"}, "status" : "DuplicateError" }`
If dup error, name field sa assignuser response/setuser response should be the current rejected username
  2. SetUsername - same reply as Login but this is specifically for changing username after the user has already login 
Response 1: `{ "mtp": "SetUsername", "data": {"name": "Bob"} , "status" : "OK"}`
Response 2: `{ "mtp": "SetUsername", "data": {"name": "Bob"} , "status" : "DuplicateError"}`
A duplicate error indicates that the server has found a user with the same username already logged in. The client attempting to join will keep sending Login requests till an OK response is sent by the server.
  2. ProvideUserInfo
`{ "mtp": "ProvideUserInfo", "data" : {"name": "Bob", ip: "127.0.0.1" , "port" : "15151"} , "status" : "OK"}`
`{ "mtp": "ProvideUserInfo", "data" : {"name": "Bob", ip: "" , "port" : ""} , "status" : "UserDoesNotExist"}`
  3. SendLocalTime
`{ "mtp": "SendLocalTime", "data" : {"time": "00:00:00" } }`
  4. WhisperFromUser
`{ "mtp": "WhisperFromUser", "data" : {"from": "Bob", "message": "This is a PM" } }`
  5. SendChatFromUser
`{ "mtp": "SendChatFromUser", "data" : {"name": "Bob", "message": "Hello World!" } }`
  6. SendOnlineList 
`{ "mtp": "SendOnlineList", "data" : { "name" : ["claudyne", "philippe" ,"keith"  ]} }`
  7. KickUser -Reply to a kick user request (sent back to the admin that requested the kick **not** the person being kicked)
`{ "mtp": "KickUser", "data" : {}, "status" : "OK" }`
`{ "mtp": "KickUser", "data" : {}, "status" : "NotAdminError" }`
`{ "mtp": "KickUser", "data" : {}, "status" : "UserDoesNotExist" }`
  8. MuteUser - Reply to a mute user request (sent back to the admin that requested the mute **not** the person being muted)
`{ "mtp": "MuteUser", "data" : {}, "status" : "OK" }`
`{ "mtp": "MuteUser", "data" : {}, "status" : "NotAdminError" }`
`{ "mtp": "MuteUser", "data" : {}, "status" : "UserDoesNotExist" }`
`{"mtp": "MuteUser", "data": {}, "status": "UserAlreadyMuted"}}`
  9. UnmuteUser - Reply to a unmute user request (sent back to the admin that requested the mute **not** the person being muted)
`{ "mtp": "UnmuteUser", "data" : {}, "status" : "OK" }`
`{ "mtp": "UnmuteUser", "data" : {}, "status" : "NotAdminError" }`
`{ "mtp": "UnmuteUser", "data" : {}, "status" : "UserDoesNotExist" }`
`{"mtp": "UnmuteUser", "data": {}, "status": "UserNotMuted"}}`
10. Kick - This is sent to the person being kicked. Forces him/her to disconnect from the server.
After which, the server will close the socket connected to the kicked client.
`{ "mtp": "Kick", "data" : {}}`
11. ServerMessage
`{ "mtp": "ServerMessage", "data" : {"message": "user1 joined the chat"} }`
`{ "mtp": "ServerMessage", "data" : {"message": "user1 has changed his/her nickname to user2"} }`
`{ "mtp": "ServerMessage", "data" : {"message": "user1 has left the chat"} }` 
`{ "mtp": "ServerMessage", "data" : {"message": "user1 has been kicked from the chat"} }` 
`{ "mtp": "ServerMessage", "data" : {"message": "user1 is now the admin"} }`
{"mtp": "ServerMessage", "data": {"message": "keith is not online in the server!"}}
12. SetAsAdmin - reply to the original admin to update if SetAsAdmin was successful
`{ "mtp": "SetAsAdmin", "data" : { "name" : "user99" },  "status": "OK" }`
`{ "mtp": "SetAsAdmin", "data" : { "name" : "user99" },  "status": "UserDoesNotExist" }`
`{ "mtp": "SetAsAdmin", "data" : { "name" : "user99" },  "status": "NotAdminError" }`
`{"mtp": "SetAsAdmin", "data": {}, "status": "AlreadyAdmin"}}`
### Special Commands  
The special commands in the MP are as follows:
-Mute User
-SetAsAdmin
-Kick User
-Whisper (Private message) 
### Admin Privileges
The server will keep track of a single admin (only one user can be an admin at a time).
- At server start, the first user to join will become the admin
- This user can pass the admin privilege to another user by sending a SetAsAdmin command
- **Only** the admin can execute kick and mute commands

### Clarifications about Kick and Mute 
Kick and Mute are admin commands. Only the **current** admin can perform them.
Example:
Admin client: `{ "mtp": "KickUser", "data" : { "name" : "user99" } }`
Server: parses and checks if user99 exists in the current list of users and if the client requesting is an admin
if the user requesting is not an admin, server sends back
 `{ "mtp": "KickUser", "data" : {}, "status" : "NotAdminError" }`
if the user cannot be found, server sends back 
`{ "mtp": "KickUser", "data" : {}, "status" : "UserDoesNotExist" }`

else if the user exists and the requesting client is an admin:
the server will send two things
1.  `{ "mtp": "KickUser", "data" : {}, "status" : "OK" }` back to the Admin client
2. `{ "mtp": "Disconnect", "data" : { "message" : "Kicked from server"}` to the person being kicked. (In this example, it's user99)

Extra Suggestion:
Parse client terminal inputs by putting / before a command. 
Ex: to send a setusername request, enter "/SetUsername New_username11" 

PS. Refer to thread below for updates on extra errors to handle

**Comment by digitalsirkeith** [comment]
AssignUsername,
KeepAliveResponse,
ServerMessage,
ServerPort: 15151 (default),

**Comment by ps-balucan** [comment]
Peer-to-Peer:
Discovery mode: Broadcast into broadcast ip periodically
{ "mtp" : "Broadcast" , "data" : { "ip" : "127.0.0.1" ,  "port" : "14444" }  

After a peer finds another peer that he/she wants to send a message to, the peer will use the ip and port received from the broadcast IP to send a UDP packet directly to the other peer using the same/similar JSON formatted message discussed for the first part.

KeepAlive:
Everyone keeps track of the broadcasts sent to the broadcast IP and keeps a keep alive timer which will decide if a peer will be removed from the 'available' list

**Comment by digitalsirkeith** [comment]
Peer-Peer:
    GetOnlineList (No login required)
    Login (Broadcasted)


Assumptions:
No more than one peer joins the network at the same time.

**Comment by ps-balucan** [comment]
Steps for finding peers:
1. Discovery broadcast message sent to **Broadcast_IP**
2. Wait for discovery response messages sent directly to your own IP/port specified in broadcast message
    - Use discovery response messages username to fill the list of online peers
Once a discovery response message indicating a valid username is received:
1. Login message is sent again to **broadcast_IP**
2. Wait for AcceptLogin message 

Once AcceptLogin message is done:
1. Continue listening in to the Broadcast IP for possible new peers

Chat/DM procedure
Chat privately with chosen IP/port found in the network (Discovery Message Response messages)

**Comment by claudynetrixie** [comment]
> AssignUsername,
> KeepAliveResponse,
> ServerMessage,
> ServerPort: 15151 (default),

ServerMessage:
 { "mtp": "ServerMessage", "data": {"message": "user1 is now offline."} }

**Comment by digitalsirkeith** [comment]
Clientbound Disconnect:
{
    "mtp": "Disconnect",
    "data": {
        "message": "Kicked from server."
    }
}
{
    "mtp": "Disconnect",
    "data": {
        "message": "Server closing."
    }
}

**Comment by digitalsirkeith** [comment]
Regarding pala sa adding '/' sa terminal commands. I think it's better na they are completely up to the programmer how they'll implement it kasi yung messages naman yung important for communication. For example:
I can use "/msg" as my whisper command and another person will use "/w". As long as the message format sent and received by the respective clients are the same. 

@ps-balucan

**Comment by digitalsirkeith** [comment]
Regarding pala sa keepAlive message. Its implementation may be too much work for its worth. I need everyone's opinion on this. 

- Like this message if you want to have it removed.
- Unlike this message if you want to keep it.

**Comment by digitalsirkeith** [comment]
If the admin leaves without setting another user as admin, the server shall choose the oldest client. This does not directly affect the messages, so you may choose a different behavior for this.

**Comment by digitalsirkeith** [comment]
Unhandled case for UserDoesNotExist: WhisperToUser

Proposal: Simply use ServerMessage to inform the source client that the requested user is not present in the server. i.e.

{"mtp": "ServerMessage", "data": {"message": "keith is not online in the server!"}}

**Comment by digitalsirkeith** [comment]
Currently encountering a case where the server/client receives two messages consecutively, resulting in concatenated two concatenated json objects. This resulting message raises an error to the native json python library. Writing this as a heads-up to anyone that may encounter this problem.

**Comment by digitalsirkeith** [comment]
I can think of three robust solutions to this problem:
- Explicitly split the message into proper json objects. This requires a complex queueing mechanism however.
- Prefix header. Encode the length of the json object into the message as a prefix. 
- Delimiter. Explicitly set a character like '\n' as the delimiter. Seeing a newline would imply that the json object is complete.

Another solution would be to simply ensure that there is "sufficient" delay between each message.  What is enough delay though?

**Comment by digitalsirkeith** [comment]
ayoko na, inaantok na ko lmao

**Comment by digitalsirkeith** [comment]
Unhandled case: Admin unmuted a player which was never muted in the first place.
Proposal: Server sends a ServerMessage informing the admin that the user is not muted. i.e. 
{"mtp": "ServerMessage", "data": {"message": "keith is not muted"}}

**Comment by digitalsirkeith** [comment]
Unhandled case: Admin mutes an already muted player.
Proposal: Server sends an UnmuteUser message with a status info: "UserAlreadyMuted" i.e.
{"mtp": "UnmuteUser", "data": {}, "status": "UserAlreadyMuted"}}

**Comment by digitalsirkeith** [comment]
Unhandled case: Admin sets himself as the admin
Proposal: Server sends an SetAsAdmin message with a status info: "AlreadyAdmin" i.e.
{"mtp": "SetAsAdmin", "data": {}, "status": "AlreadyAdmin"}}

**Comment by claudynetrixie** [comment]
> Unhandled case: Admin unmuted a player which was never muted in the first place.
> Proposal: Server sends a MuteUser message with a status info: "UserNotMuted" i.e.
> {"mtp": "MuteUser", "data": {}, "status": "UserNotMuted"}}

better ata if the mtp for the one above is "UnmuteUser" and "MuteUser" for the one below? 

> Unhandled case: Admin mutes an already muted player.
> Proposal: Server sends an UnmuteUser message with a status info: "UserAlreadyMuted" i.e.
> {"mtp": "UnmuteUser", "data": {}, "status": "UserAlreadyMuted"}}

**Comment by digitalsirkeith** [comment]
> > Unhandled case: Admin unmuted a player which was never muted in the first place.
> > Proposal: Server sends a MuteUser message with a status info: "UserNotMuted" i.e.
> > {"mtp": "MuteUser", "data": {}, "status": "UserNotMuted"}}
> 
> better ata if the mtp for the one above is "UnmuteUser" and "MuteUser" for the one below?
> 
> > Unhandled case: Admin mutes an already muted player.
> > Proposal: Server sends an UnmuteUser message with a status info: "UserAlreadyMuted" i.e.
> > {"mtp": "UnmuteUser", "data": {}, "status": "UserAlreadyMuted"}}

woops, baliktad nasulat ako. edited accordingly.

**Comment by digitalsirkeith** [comment]
> 3\. `{ "mtp": "ProvideUserInfo", "data" : {"name": "Bob", ip: "127.0.0.1" , "port" : "15151"} , "status" : "OK"}`
>     `{ "mtp": "ProvideUserInfo", "data" : {"name": "Bob", ip: "" , "port" : ""} , "status" : "UserDoesNotExist"}`

JSON supports integers naman. I think port value shouldn't be enclosed in quotation marks: 
{ "mtp": "ProvideUserInfo", "data" : {"name": "Bob", ip: "127.0.0.1" , "port" : 15151} , "status" : "OK"}`

**Comment by digitalsirkeith** [comment]
Message Formats Finished.
